Repository svelte-plugins/tooltips, pull requests merged in 2023-11, with the labels that each got.

#20 refactor(tooltips): add show prop to interface for manual control of showing/hiding
  README.md
  docs/src/App.svelte
  package-lock.json
  package.json
  src/action-tooltip.snap.js
  src/action-tooltip.svelte
  src/action-tooltip.svelte.d.ts
  src/action.js
  src/index.d.ts
  src/tooltip.svelte
  src/tooltip.svelte.d.ts
Labels: Priority: Low, Type: Feature, Type: Refactor

#21 refactor(tooltips): use absolute positioning with tooltips
  package.json
  src/action-tooltip.snap.js
  src/action-tooltip.svelte
  src/action-tooltip.svelte.d.ts
  src/action.js
  src/helpers.js
  src/tooltip.snap.js
  src/tooltip.svelte
Labels: Type: Refactor

#22 feat(tooltips): add delay prop
  README.md
  src/action-tooltip.svelte
  src/action-tooltip.svelte.d.ts
  src/tooltip.svelte
  src/tooltip.svelte.d.ts
Labels: Priority: Low, Type: Feature
